### ISSUE TITLE
JSON Log rules for allowing and not allowing some of patterns. 

### ISSUE THREAD

**Issue by KunalSin9h** [KunalSin9h/livejq#6]
This will help in reducing log output size, because it can be overwhelming to see long JSON logs.

**Comment by KunalSin9h** [comment]
maybe create a `livejq.yaml` file for rules etc.

**Comment by KunalSin9h** [comment]
when `-F` flag is not given it will run the `default` filter. 

```bash
npm start | livejq
```

This will run memory filter
```bash
npm start | livejq -F memory
```

This will run both memory and stack filter
```bash
npm start | livejq -F memory stack
```

```toml
[default]
allow = [ "*", "clientPort" ]
disallow = [ "transactionID" ]

[memory]
allow = [ "memoryAddress" ]

[stack]
allow = [ "stackTracePID" ]
```
